version: 2
updates:
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Python (pip) dependency updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "tensorflow"   # Optional: example to ignore specific deps
        versions: ["<2.0"]

  # Dockerfile updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
