version: "3.9"

services:
  nodebot:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add your environment vars here
    depends_on:
      - pybackend

  pybackend:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    environment:
      - PYTHON_ENV=production
      # Add your environment vars here
