name: Build & Deploy Script Analyzer Bot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Define travis_cmd and travis_retry functions and run build & deploy
        shell: bash
        run: |
          travis_cmd() {
            echo -e "\033[32;1mRunning: $1\033[0m"
            eval "$1"
            local result=$?
            if [ $result -ne 0 ]; then
              echo -e "\033[31;1mCommand failed: $1\033[0m"
              exit $result
            fi
          }

          travis_retry() {
            local count=0
            local result=1
            until [ $count -ge 3 ]; do
              "$@" && result=0 && break
              count=$((count + 1))
              echo -e "\033[31;1mRetry $count failed. Retrying...\033[0m"
              sleep 1
            done
            return $result
          }

          travis_cmd "npm run build"
          travis_cmd "npm run deploy"

      - name: Send Discord deployment notification
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "✅ Deployment of Script Analyzer Bot complete!"}' \
            "${{ secrets.DISCORD_WEBHOOK }}"
